/**
 * Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.
题意：给两个字符串s、t。其中t是由s随机打乱后再在随机位置加一个字符组成的。让你找出那个加的字符。
思路：因为s、t都确定了是小写字母组成的，可以用数组统计每个char的出现次数，最后看t里面哪个char出现次数多了一次就行了。
 */




class Solution {
    int [] has= new int[30];
    public char findTheDifference(String s, String t) {
        
        for(int i=0;i<s.length();i++)
            has[(int)(s.charAt(i)-'a')]++;
        for(int i=0;i<t.length();i++)
            has[(int)(t.charAt(i)-'a')]--;
        for(int i=0;i<30;i++)
                if(has[i]<0)
                    return (char)(i+'a');
        return 'p';//这是随便来的
    }
}